<?php
/**
 * Helper functions.
 */

// ── Excerpt ──────────────────────────────────────────────────────────────────
add_filter( 'excerpt_length', fn() => 25 );
add_filter( 'excerpt_more',   fn() => '...' );

// ── Megamenu panels ──────────────────────────────────────────────────────────

/**
 * Renders megamenu panels for every top-level primary-nav item that has children.
 *
 * Menu depth mapping:
 *   depth 0 → nav trigger (rendered by CPNRP_Nav_Walker)
 *   depth 1 → megamenu column header  (link or plain label)
 *   depth 2 → megamenu list link
 *
 * Panel ID: sanitize_title( $item->title ) . '-panel'
 * Must match the data-target generated by the Walker.
 *
 * Optional info box per panel: set via Customizer key
 *   cpnrp_megamenu_{slug}_info  (e.g. cpnrp_megamenu_pro-rodiny_info)
 */
function cpnrp_render_megamenu_panels() {
	$locations = get_nav_menu_locations();
	if ( empty( $locations['primary'] ) ) return;

	$items = wp_get_nav_menu_items( $locations['primary'] );
	if ( ! $items ) return;

	// Build children map: parent_id → [ child_item, ... ]
	$children = [];
	foreach ( $items as $item ) {
		$parent = (int) $item->menu_item_parent;
		if ( $parent ) {
			$children[ $parent ][] = $item;
		}
	}

	foreach ( $items as $item ) {
		// Only process top-level items that have at least one child
		if ( (int) $item->menu_item_parent !== 0 ) continue;
		if ( empty( $children[ $item->ID ] ) ) continue;

		$slug     = sanitize_title( $item->title );
		$panel_id = $slug . '-panel';
		?>
		<div class="megamenu-panel" id="<?php echo esc_attr( $panel_id ); ?>">
			<div class="container">
				<div class="megamenu-grid">

					<?php foreach ( $children[ $item->ID ] as $col ) : ?>
						<div class="megamenu-column">

							<?php
							// Column header: link if URL is set, otherwise plain label
							$col_url = trim( $col->url ?? '' );
							$has_url = $col_url && $col_url !== '#' && $col_url !== home_url( '/' );
							?>
							<?php if ( $has_url ) : ?>
								<a href="<?php echo esc_url( $col_url ); ?>" class="megamenu-title">
									<?php echo esc_html( $col->title ); ?>
								</a>
							<?php else : ?>
								<span class="megamenu-title">
									<?php echo esc_html( $col->title ); ?>
								</span>
							<?php endif; ?>

							<?php if ( ! empty( $children[ $col->ID ] ) ) : ?>
								<ul class="megamenu-list">
									<?php foreach ( $children[ $col->ID ] as $link ) : ?>
										<li>
											<a href="<?php echo esc_url( $link->url ); ?>">
												<?php echo esc_html( $link->title ); ?>
											</a>
										</li>
									<?php endforeach; ?>
								</ul>
							<?php endif; ?>

						</div>
					<?php endforeach; ?>

				</div>

				<?php
				// Optional info box — editable via Customizer
				$defaults = [
					'pro-rodiny' => 'Teprve se rozhodujete? <a href="/kontakt">Napište nám</a> — rádi odpovíme na všechny otázky bez závazku.',
				];
				$info = get_theme_mod( 'cpnrp_megamenu_' . $slug . '_info', $defaults[ $slug ] ?? '' );
				if ( $info ) :
				?>
					<div class="megamenu-info">
						<?php echo wp_kses_post( $info ); ?>
					</div>
				<?php endif; ?>

			</div>
		</div>
		<?php
	}
}
